# Embed binary font files into a target.
#   ggui_embed_font(<target> <symbol> <file>)
# Defines `extern "C" const unsigned char <symbol>[]` and `extern "C" const unsigned long long
# <symbol>_size`. GCC/Clang (Linux, MinGW) use .incbin so a 10 MB font costs no compile time;
# MSVC gets a generated byte array (EmbedFontGen.cmake).

function(ggui_embed_font target symbol file)
    set(out ${CMAKE_BINARY_DIR}/generated/fonts/${symbol}.c)
    if(MSVC)
        add_custom_command(OUTPUT ${out}
            COMMAND ${CMAKE_COMMAND} -DINPUT=${file} -DOUTPUT=${out} -DSYMBOL=${symbol}
                    -P ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/EmbedFontGen.cmake
            DEPENDS ${file} ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/EmbedFontGen.cmake
            COMMENT "Embedding ${symbol}")
    else()
        if(WIN32)
            set(section ".section .rdata,\\\"dr\\\"")
            set(restore ".text")      # PE/COFF gas has no .previous
        else()
            set(section ".section .rodata")
            set(restore ".previous")
        endif()
        file(CONFIGURE OUTPUT ${out} CONTENT [=[
/* Generated by EmbedFont.cmake. Do not edit. */
__asm__(
    "@section@\n"
    ".global @symbol@\n"
    ".balign 16\n"
    "@symbol@:\n"
    ".incbin \"@file@\"\n"
    ".global @symbol@_end\n"
    "@symbol@_end:\n"
    ".byte 0\n"
    "@restore@\n");
extern const unsigned char @symbol@[];
extern const unsigned char @symbol@_end[];
unsigned long long @symbol@_size_value(void);
unsigned long long @symbol@_size_value(void) { return (unsigned long long)(@symbol@_end - @symbol@); }
]=] @ONLY)
        set_source_files_properties(${out} PROPERTIES OBJECT_DEPENDS ${file})
    endif()
    target_sources(${target} PRIVATE ${out})
endfunction()
