# Script mode helper for EmbedFont.cmake on MSVC: writes INPUT as a C byte array.
file(READ ${INPUT} hex HEX)
string(LENGTH "${hex}" len)
math(EXPR size "${len} / 2")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
string(REGEX REPLACE "((0x..,){32})" "\\1\n" bytes "${bytes}")
file(WRITE ${OUTPUT} "/* Generated by EmbedFontGen.cmake. Do not edit. */\n"
    "const unsigned char ${SYMBOL}[] = {\n${bytes}0x00};\n"
    "unsigned long long ${SYMBOL}_size_value(void);\n"
    "unsigned long long ${SYMBOL}_size_value(void) { return ${size}ULL; }\n")
