# Install rules and CPack ZIP: ggui and git-gg side by side, so `git gg` resolves on PATH.
include(GNUInstallDirs)
install(TARGETS git-gg RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
if(GGUI_BUILD_APP)
    install(TARGETS ggui RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
    if(UNIX AND NOT APPLE)
        install(FILES ${PROJECT_SOURCE_DIR}/res/ggui.desktop DESTINATION ${CMAKE_INSTALL_DATADIR}/applications)
        install(FILES ${PROJECT_SOURCE_DIR}/res/ggui.png
            DESTINATION ${CMAKE_INSTALL_DATADIR}/icons/hicolor/256x256/apps)
    endif()
endif()
install(FILES ${PROJECT_SOURCE_DIR}/LICENSE DESTINATION ${CMAKE_INSTALL_DOCDIR})

set(CPACK_PACKAGE_NAME ggui)
set(CPACK_PACKAGE_VENDOR "ggui")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Git GUI with first-class conflicts and undo")
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_RESOURCE_FILE_LICENSE ${PROJECT_SOURCE_DIR}/LICENSE)
if(WIN32)
    set(CPACK_GENERATOR ZIP)
else()
    set(CPACK_GENERATOR "ZIP;TGZ")
endif()
include(CPack)
